apiVersion: 1
datasources:
  - name: ZEVENT
    uid: zevent-pg
    type: grafana-postgresql-datasource
    url: db:5432
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      database: zevent
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
